// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSiAAi92JuGzUZe_bAUVkGFdX-rekhcjk',
    appId: '1:759793755680:web:3dfb426429011d99e7be45',
    messagingSenderId: '759793755680',
    projectId: 'ai-tutor-26fe2',
    authDomain: 'ai-tutor-26fe2.firebaseapp.com',
    storageBucket: 'ai-tutor-26fe2.firebasestorage.app',
    measurementId: 'G-RBW5V82FBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUm-tTWvrIIv72bFSOFmARDWgXHE2VN0Y',
    appId: '1:759793755680:android:f962af7b7ffba0dfe7be45',
    messagingSenderId: '759793755680',
    projectId: 'ai-tutor-26fe2',
    storageBucket: 'ai-tutor-26fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy2Vqu6-BHVBThwTLy_vFUV9Bu0PrUsaQ',
    appId: '1:759793755680:ios:b1c946b029c902a6e7be45',
    messagingSenderId: '759793755680',
    projectId: 'ai-tutor-26fe2',
    storageBucket: 'ai-tutor-26fe2.firebasestorage.app',
    iosClientId: '759793755680-3f4085hf57qd18t9k0vq2kkvj0bcr4bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy2Vqu6-BHVBThwTLy_vFUV9Bu0PrUsaQ',
    appId: '1:759793755680:ios:b1c946b029c902a6e7be45',
    messagingSenderId: '759793755680',
    projectId: 'ai-tutor-26fe2',
    storageBucket: 'ai-tutor-26fe2.firebasestorage.app',
    iosClientId: '759793755680-3f4085hf57qd18t9k0vq2kkvj0bcr4bi.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSiAAi92JuGzUZe_bAUVkGFdX-rekhcjk',
    appId: '1:759793755680:web:f71356f27167b0e2e7be45',
    messagingSenderId: '759793755680',
    projectId: 'ai-tutor-26fe2',
    authDomain: 'ai-tutor-26fe2.firebaseapp.com',
    storageBucket: 'ai-tutor-26fe2.firebasestorage.app',
    measurementId: 'G-0M8914XKT9',
  );
}
