// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRMJLXrrntsnj-SkKlkR6EyHFb-mjQp6Y',
    appId: '1:356162494187:web:914d49b30078e762dca8ae',
    messagingSenderId: '356162494187',
    projectId: 'ai-tutor-project-b43c2',
    authDomain: 'ai-tutor-project-b43c2.firebaseapp.com',
    storageBucket: 'ai-tutor-project-b43c2.firebasestorage.app',
    measurementId: 'G-G25XSNGDCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvkiAQKhhxf7ZT7crOxcrVC7fcymStjAI',
    appId: '1:356162494187:android:b75c9be0d692addcdca8ae',
    messagingSenderId: '356162494187',
    projectId: 'ai-tutor-project-b43c2',
    storageBucket: 'ai-tutor-project-b43c2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSHFpUURxEm7s6qN14I2oF375dnmW6_5g',
    appId: '1:356162494187:ios:72e6669fc08cd07fdca8ae',
    messagingSenderId: '356162494187',
    projectId: 'ai-tutor-project-b43c2',
    storageBucket: 'ai-tutor-project-b43c2.firebasestorage.app',
    iosBundleId: 'com.example.aiTutor',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSHFpUURxEm7s6qN14I2oF375dnmW6_5g',
    appId: '1:356162494187:ios:72e6669fc08cd07fdca8ae',
    messagingSenderId: '356162494187',
    projectId: 'ai-tutor-project-b43c2',
    storageBucket: 'ai-tutor-project-b43c2.firebasestorage.app',
    iosBundleId: 'com.example.aiTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRMJLXrrntsnj-SkKlkR6EyHFb-mjQp6Y',
    appId: '1:356162494187:web:8a2d174b3d811772dca8ae',
    messagingSenderId: '356162494187',
    projectId: 'ai-tutor-project-b43c2',
    authDomain: 'ai-tutor-project-b43c2.firebaseapp.com',
    storageBucket: 'ai-tutor-project-b43c2.firebasestorage.app',
    measurementId: 'G-XL2Y4KF3V0',
  );
}
